name: Regression Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '20 17 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Cypress dependencies and run regression tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: false
          command: npm run test:regression